=== Hamosad1657/HamosadScoutingApp2/hamosad_scouting_app_2/schema/schemas/app.schema.json
{
	"$schema": "http://json-schema.org/draft-04/schema#",
	"title": "Scouting App",
	"description": "A scouting app designed in JSON.",
	"type": "object",
	"required": [
		"name"
	],
	"properties": {
		"name": {
			"description": "The name of the app.",
			"type": "string"
		},
		"teamNumber": {
			"description": "The number of your team.",
			"type": "integer"
		},
		"pages": {
			"description": "The pages of the app that aren't a part of any report.",
			"type": "object",
			"properties": {
				"home": {
					"$ref": "homePage.schema.json"
				}
			},
			"required": [
				"home"
			],
			"patternProperties": {
				"^[a-z]+([a-z][A-Z])*": {
					"$ref": "page.schema.json"
				}
			}
		},
		"reports": {
			"type": "object",
			"patternProperties": {
				"^[a-z]+([a-z][A-Z])*": {
					"$ref": "report.schema.json"
				}
			}
		}
	}
}

=== Hamosad1657/HamosadScoutingApp2/hamosad_scouting_app_2/schema/scouting.json
{
	"$schema": "./schemas/app.schema.json",
	"name": "Hamosad Scouting App 2",
	"teamNumber": 1657,
	"pages": {
		"home": {
			"title": "Hamosad Scouting App",
			"logo": "assets/images/hamosadLogoGreen.png",
			"widgets": {
				"name": {
					"type": "textInput",
					"hint": "Enter your name..."
				},
				"teamNumber": {
					"type": "textInput",
					"hint": "Enter your team number...",
					"onlyNumbers": true
				}
			}
		},
		"about": {
			"title": "About",
			"icon": "info_outline",
			"widgets": {
				"madeWith": {
					"type": "flutterLogo",
					"title": "This app was made with"
				},
				"madeBy": {
					"type": "specialText",
					"title": "This app was made by",
					"text": "Sufi Levy",
					"font": "",
					"color": "0x165700"
				},
				"madeFor": {
					"type": "image",
					"title": "This app was made for",
					"path": "assets/images/hamosadLogo.png"
				}
			}
		}
	},
	"reports": {
		"game": {
			"description": "Game Report - A mid-game report about the robot's performance.",
			"pages": {
				"generalInformation": {
					"title": "General Information",
					"icon": "",
					"widgets": {
						"gameNumber": {
							"type": "gameNumber",
							"title": "Game Number",
							"includeFinals": true,
							"includePractice": true
						},
						"teamNumber": {
							"type": "teamNumber"
						}
					}
				},
				"autonomous": {
					"title": "Autonomous",
					"icon": "",
					"widgets": {
						"exitedTarmac": {
							"type": "toggleButton",
							"title": "Has the robot exited the tarmac?",
							"score": 2
						},
						"ballsPickedFeeder": {
							"type": "counter",
							"title": "Balls picked from feeder",
							"min": 0,
							"max": 999,
							"step": 1
						},
						"ballsPickedFloor": {
							"type": "counter",
							"title": "Balls picked from the floor",
							"min": 0,
							"max": 999,
							"step": 1
						},
						"ballsMissed": {
							"type": "counter",
							"title": "Balls missed",
							"min": 0,
							"max": 999,
							"step": 1
						},
						"ballsLower": {
							"type": "counter",
							"title": "Balls entered lower hub",
							"min": 0,
							"max": 999,
							"step": 1,
							"score": 2
						},
						"ballsUpper": {
							"type": "counter",
							"title": "Balls entered upper hub",
							"min": 0,
							"max": 999,
							"step": 1,
							"score": 4
						},
						"notes": {
							"type": "notes",
							"title": "Additional notes"
						}
					}
				},
				"teleop": {
					"title": "Teleop",
					"icon": "",
					"widgets": {
						"needsAnchor": {
							"type": "toggleButton",
							"title": "Does the robot need an anchor point to shoot?"
						},
						"anchorPoint": {
							"type": "textInput",
							"hint": "Anchor point...",
							"optional": "needsAnchor"
						},
						"ballsPickedFeeder": {
							"type": "counter",
							"title": "Balls picked from feeder",
							"min": 0,
							"max": 999,
							"step": 1
						},
						"ballsPickedFloor": {
							"type": "counter",
							"title": "Balls picked from the floor",
							"min": 0,
							"max": 999,
							"step": 1
						},
						"ballsMissed": {
							"type": "counter",
							"title": "Balls missed",
							"min": 0,
							"max": 999,
							"step": 1
						},
						"ballsLower": {
							"type": "counter",
							"title": "Balls entered lower hub",
							"min": 0,
							"max": 999,
							"step": 1,
							"score": 1
						},
						"ballsUpper": {
							"type": "counter",
							"title": "Balls entered upper hub",
							"min": 0,
							"max": 999,
							"step": 1,
							"score": 2
						},
						"notes": {
							"type": "notes",
							"title": "Additional notes"
						}
					}
				},
				"endgame": {
					"title": "Endgame",
					"icon": "",
					"widgets": {
						"sliderClimbed": {
							"type": "slider",
							"title": "Robot has climbed to slider...",
							"min": 0,
							"max": 4,
							"step": 1,
							"score": [
								0,
								4,
								6,
								10,
								15
							]
						},
						"timeClimbed": {
							"type": "stopwatch",
							"title": "Time took to climb"
						},
						"notes": {
							"type": "notes",
							"title": "Additional notes"
						}
					}
				},
				"summary": {
					"title": "Summary",
					"icon": "",
					"widgets": {
						"robotFocus": {
							"type": "slider",
							"title": "Robot's main focus",
							"subtitle": "< Scoring        Defending >",
							"min": 1,
							"max": 5,
							"step": 1
						},
						"pointsSummary": {
							"type": "pointsSummary"
						}
					}
				}
			}
		}
	}
}
